# Generated by Django 3.0.4 on 2020-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='code',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
