# Generated by Django 3.0.4 on 2020-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_number_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='code',
        ),
        migrations.AddField(
            model_name='number',
            name='itle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
