# Generated by Django 3.0.4 on 2020-03-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200325_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='sqrt',
        ),
        migrations.RemoveField(
            model_name='number',
            name='square',
        ),
    ]
