# Generated by Django 3.0.4 on 2020-03-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20200325_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='itle',
        ),
    ]
