# Generated by Django 3.0.4 on 2020-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20200325_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='sqrt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='number',
            name='square',
            field=models.BigIntegerField(default=0),
        ),
    ]
