# Generated by Django 3.0.4 on 2020-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20200325_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='nolookfield',
            field=models.BigIntegerField(default=69),
        ),
    ]
