# Generated by Django 3.0.4 on 2020-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='Files/None/No-img.pdf', upload_to='Files/'),
        ),
    ]
