# Generated by Django 3.0.5 on 2020-04-14 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0013_number_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieved', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('token', models.CharField(blank=True, default='', max_length=100)),
                ('meanTWA', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['retrieved'],
            },
        ),
    ]
