# Generated by Django 3.0.5 on 2020-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_warp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warp',
            name='url',
            field=models.TextField(default='aaaaa'),
        ),
    ]
