# Generated by Django 3.0.5 on 2020-04-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_auto_20200415_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warp',
            old_name='token',
            new_name='warp_token',
        ),
        migrations.RenameField(
            model_name='warp',
            old_name='url',
            new_name='warp_url',
        ),
    ]
