# Generated by Django 3.0.5 on 2020-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_auto_20200421_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warp',
            name='meanCOG',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='warp',
            name='meanSOG',
            field=models.FloatField(),
        ),
    ]
