# Generated by Django 3.0.5 on 2020-04-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_auto_20200415_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warp',
            old_name='meanTWA',
            new_name='meanSOG',
        ),
    ]
