# Generated by Django 3.0.5 on 2020-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0018_auto_20200415_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warp',
            name='meanSOG',
            field=models.FloatField(),
        ),
    ]
