# Generated by Django 3.0.5 on 2020-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0018_auto_20200425_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warp',
            old_name='event',
            new_name='event_id',
        ),
        migrations.AddField(
            model_name='warp',
            name='TWD',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='warp',
            name='TWS',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='warp',
            name='start',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='warp',
            name='stop',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
