# Generated by Django 3.0.5 on 2020-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0019_auto_20200415_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warp',
            old_name='warp_url',
            new_name='boat_id',
        ),
        migrations.RenameField(
            model_name='warp',
            old_name='warp_token',
            new_name='event',
        ),
        migrations.AddField(
            model_name='warp',
            name='meanCOG',
            field=models.FloatField(default=0),
        ),
    ]
