# Generated by Django 3.0.5 on 2020-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0020_auto_20200420_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warp',
            name='meanCOG',
            field=models.FloatField(),
        ),
    ]
